version: 2.1
orbs:
  firebase-deploy: cloudliner/firebase-deploy@0.0.2
  rollbar: rollbar/deploy@volatile
jobs:
  build-and-deploy:
    docker:
      - image: cypress/base:10
    steps:
      - rollbar/notify_deploy_started:
          environment: production
      - run:
          name: Install jq
          command: |
            apt-get update && apt-get install jq
      - checkout
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - run: yarn ci
      - firebase-deploy/deploy:
          token: $FIREBASE_TOKEN
      - rollbar/notify_deploy_finished:
          deploy_id: $ROLLBAR_DEPLOY_ID
          status: succeeded
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
