enum ErrorCode {
  SURVEY_INSTANCE_NOT_FOUND = 'SURVEY_INSTANCE_NOT_FOUND',
  MULTIPLE_SURVEY_INSTANCES_FOUND = 'MULTIPLE_SURVEY_INSTANCES_FOUND',
  ANONYMOUS_USER_NULL = 'ANONYMOUS_USER_NULL',
  SURVEY_DOES_NOT_EXIST = 'SURVEY_DOES_NOT_EXIST',
  NO_USER = 'NO_USER',
}

export default ErrorCode;
